# Generated by Django 2.2 on 2020-09-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20200908_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='cutomer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
