# Generated by Django 2.2 on 2020-09-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billingprofile_cutomer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='cutomer_id',
            new_name='customer_id',
        ),
    ]
